name: olist
version: "1.0.0"
profile: olist

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

clean-targets: ["target", "dbt_packages"]

models:
  olist:
    staging:
      +schema: staging
      +materialized: view
