repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.csv$
      - id: trailing-whitespace
        exclude: \.csv$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff lint
        entry: uv run sqlfluff lint
        language: system
        files: ^dbt/(models|macros|tests)/.*\.sql$
