"""Run every compiled dbt analysis and write the results to docs/findings.md.

Run `dbt compile --select resource_type:analysis` first (make findings does both).
Every number quoted in the README comes from this file.

Usage: python scripts/run_analyses.py [--output docs/findings.md]
"""

import argparse
import sys
from datetime import date
from decimal import Decimal
from pathlib import Path

import psycopg

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ingestion.config import PROJECT_ROOT, DatabaseSettings

ANALYSES_DIR = PROJECT_ROOT / "dbt" / "analyses"
COMPILED_DIR = PROJECT_ROOT / "dbt" / "target" / "compiled" / "olist" / "analyses"
DEFAULT_OUTPUT = PROJECT_ROOT / "docs" / "findings.md"


def title_of(sql_file: Path) -> str:
    first_line = sql_file.read_text().splitlines()[0]
    return first_line.removeprefix("--").strip()


def format_value(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, Decimal):
        # keep the scale returned by PostgreSQL (round(x, 2) -> 2 decimals)
        decimals = max(0, -value.as_tuple().exponent)
        return f"{value:,.{decimals}f}"
    if isinstance(value, float):
        return f"{value:,.2f}"
    if isinstance(value, date):
        return value.isoformat()
    return str(value)


def to_markdown(columns: list[str], rows: list[tuple]) -> str:
    lines = ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]
    lines += ["| " + " | ".join(format_value(v) for v in row) + " |" for row in rows]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    sources = sorted(ANALYSES_DIR.glob("*.sql"))
    sections = [
        "# Findings",
        "",
        "> Generated by `make findings` from the queries in `dbt/analyses/`. Do not edit by hand.",
    ]
    with psycopg.connect(DatabaseSettings.from_env().conninfo()) as conn:
        for source in sources:
            compiled = COMPILED_DIR / source.name
            if not compiled.is_file():
                raise FileNotFoundError(f"{compiled} missing: run `make findings`")
            cursor = conn.execute(compiled.read_text())
            columns = [column.name for column in cursor.description]
            rows = cursor.fetchall()
            sections += [
                "",
                f"## {title_of(source)}",
                "",
                f"Query: [`dbt/analyses/{source.name}`](../dbt/analyses/{source.name})",
                "",
                to_markdown(columns, rows),
            ]
            print(f"  {source.name:<36} {len(rows):>3} rows")

    args.output.write_text("\n".join(sections) + "\n")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
